### ISSUE TITLE
Create comunication channel for development

### ISSUE THREAD

**Issue by malbernaz** [grafoojs/grafoo#85]
@adjourn and @mogelbrod, slack, discord or something else?

**Comment by adjourn** [comment]
Im using Slack for several libraries' channels, can't tell you anything about others, never used.

**Comment by mogelbrod** [comment]
Slack sounds good for me!

**Comment by adjourn** [comment]
How's it going? Would love to discuss few things.

**Comment by malbernaz** [comment]
I've created a slack channel. I'm looking for something to help people auto invite then self. Do you have an idea?

**Comment by adjourn** [comment]
Never opened a wordspace myself, `slate` library seems to use [this](https://github.com/rauchg/slackin).
 
[Ctrl+F here and search for Slack](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md).

**Comment by adjourn** [comment]
Never opened a workspace myself, `slate` library seems to use [this](https://github.com/rauchg/slackin).
 
[Ctrl+F here and search for Slack](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md).

**Comment by malbernaz** [comment]
https://grafoojs-slack.now.sh/

Can you guys please test this out?

**Comment by malbernaz** [comment]
cc @mogelbrod @adjourn

**Comment by adjourn** [comment]
I get 503 after several minutes of loading.

**Comment by mogelbrod** [comment]
Yeah, not working for me either.

**Comment by malbernaz** [comment]
I'll take a look at that

**Comment by malbernaz** [comment]
https://grafoo-slack.herokuapp.com/

I this is working now.

**Comment by malbernaz** [comment]
I'm closing this, since the problem has been solved!
